name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *' # 毎月1回、自動で実行
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1 # 自動でリポジトリをアクティブに保つAction